#!/bin/sh
# =============================================================================
# events.sh — Network Event Detection for QManager
# =============================================================================
# Sourced by qmanager_poller. Detects changes in network state and appends
# events to the NDJSON events file for the Recent Activities component.
#
# Dependencies: qlog_* functions, global state variables from poller
# Install location: /usr/lib/qmanager/events.sh
#
# Global variables used (defined in poller):
#   Read:  network_type, lte_band, lte_pci, nr_band, nr_pci, nr_state,
#          modem_reachable, conn_internet_available, conn_latency,
#          conn_avg_latency, conn_packet_loss, t2_ca_active, t2_ca_count,
#          t2_nr_ca_active, t2_nr_ca_count, t2_carrier_components,
#          service_status
#   Write: prev_ev_*, ev_high_lat_streak, ev_high_loss_streak,
#          ev_lat_alerted, ev_loss_alerted, events_initialized
# =============================================================================

[ -n "$_EVENTS_LOADED" ] && return 0
_EVENTS_LOADED=1

PCI_STATE_FILE="/tmp/qmanager_pci_state.json"
EVENT_STATE_FILE="${EVENT_STATE_FILE:-/tmp/qmanager_event_state.json}"

# ---------------------------------------------------------------------------
# Quality threshold config — drives high_latency / high_packet_loss events
# ---------------------------------------------------------------------------
QUALITY_CONFIG="${QUALITY_CONFIG:-/etc/qmanager/quality_thresholds.json}"
QUALITY_RELOAD_FLAG="${QUALITY_RELOAD_FLAG:-/tmp/qmanager_events_reload}"

# Defaults match the "tolerant" preset; survive a missing or malformed JSON.
_qt_lat_thresh=250
_qt_lat_debounce=3
_qt_loss_thresh=30
_qt_loss_debounce=3

_qt_apply_lat() {
    case "$1" in
        standard)      _qt_lat_thresh=150; _qt_lat_debounce=3 ;;
        tolerant)      _qt_lat_thresh=250; _qt_lat_debounce=3 ;;
        very-tolerant) _qt_lat_thresh=500; _qt_lat_debounce=2 ;;
    esac
}

_qt_apply_loss() {
    case "$1" in
        standard)      _qt_loss_thresh=15; _qt_loss_debounce=3 ;;
        tolerant)      _qt_loss_thresh=30; _qt_loss_debounce=3 ;;
        very-tolerant) _qt_loss_thresh=50; _qt_loss_debounce=2 ;;
    esac
}

_qt_load() {
    [ -f "$QUALITY_CONFIG" ] || return 0
    local lat loss
    lat=$(jq -r '.latency.preset // "tolerant"' "$QUALITY_CONFIG" 2>/dev/null)
    loss=$(jq -r '.loss.preset // "tolerant"' "$QUALITY_CONFIG" 2>/dev/null)
    if [ -z "$lat" ] || [ -z "$loss" ]; then
        qlog_warn "quality_thresholds.json parse failed, keeping current thresholds"
        return 0
    fi
    case "$lat"  in standard|tolerant|very-tolerant) _qt_apply_lat  "$lat"  ;; esac
    case "$loss" in standard|tolerant|very-tolerant) _qt_apply_loss "$loss" ;; esac
}

_qt_check_reload() {
    [ -f "$QUALITY_RELOAD_FLAG" ] || return 0
    _qt_load
    rm -f "$QUALITY_RELOAD_FLAG"
    qlog_info "Quality thresholds reloaded: lat=${_qt_lat_thresh}ms/${_qt_lat_debounce} loss=${_qt_loss_thresh}%/${_qt_loss_debounce}"
}

# Initial load on first source. After this, only the reload flag triggers re-reads.
_qt_load

# ---------------------------------------------------------------------------
# CROSS-UID WRITE RULES FOR $EVENTS_FILE (/tmp/qmanager_events.json)
# ---------------------------------------------------------------------------
# This file is appended to by BOTH uids: root (qmanager_poller, qmanager_watchcat,
# qmanager_tower_failover) and www-data (cellular/apn.sh, profiles/deactivate.sh,
# profile_mgr.sh's lazy loader — every CGI that sources this lib).
#
# /tmp is root-owned, mode 1777 (sticky), and this kernel runs with
# fs.protected_regular=1. Together that means:
#   * A regular file in /tmp can only be opened for write by another uid if
#     file_owner == dir_owner (i.e. root-owned) OR caller == file_owner. Root
#     gets NO override — root cannot write a www-data-owned file here either.
#   * Only the file's owner (or root) may unlink or rename over it.
# So root:root 0666 is the ONE ownership under which both uids can append.
# Whoever creates the file first decides that, forever.
#
# _events_ensure_file() below is a BACKSTOP, not the fix: when ROOT creates the
# file it yields root:root 0666 and everything works, but when WWW-DATA wins
# the race the file is www-data-owned and ROOT is then blocked from appending —
# and no chmod can undo that. The real fix is a boot-time root seed (handled
# separately, alongside the /tmp/qmanager.log seed in qmanager_setup); this
# helper only stops the common case of a total silent loss.
_events_ensure_file() {
    [ -e "$EVENTS_FILE" ] && return 0
    : > "$EVENTS_FILE" 2>/dev/null || return 1
    chmod 666 "$EVENTS_FILE" 2>/dev/null
    return 0
}

# Append a single event to the events file (NDJSON — one JSON per line)
# Note: All message content is generated by us (band names, PCI numbers, etc.)
# so no user-input escaping is needed.
append_event() {
    local etype="$1" message="$2" severity="${3:-info}"
    local ts
    ts=$(date +%s)

    if ! _events_ensure_file; then
        qlog_warn "EVENT DROPPED [${etype}] ${message} — cannot create $EVENTS_FILE"
        return 1
    fi

    # The append is CHECKED. It used to be fire-and-forget with an
    # unconditional success log below it, so a cross-uid EACCES (see the note
    # above) lost the event AND claimed in the log that it had been recorded.
    if ! jq -n -c \
        --argjson ts "$ts" \
        --arg type "$etype" \
        --arg message "$message" \
        --arg severity "$severity" \
        '{timestamp: $ts, type: $type, message: $message, severity: $severity}' >> "$EVENTS_FILE" 2>/dev/null; then
        qlog_warn "EVENT DROPPED [${etype}] ${message} — append to $EVENTS_FILE failed (owner/permission denied; expected root:root 0666)"
        return 1
    fi

    # Trim to max entries.
    # INODE-PRESERVING — this must NEVER go back to `mv`. A rename here (a) is
    # refused outright for a cross-uid caller because /tmp is sticky, and (b)
    # when it does succeed, replaces the shared root:root 0666 inode with one
    # owned by whoever trimmed, at their umask (0644) — which is precisely how
    # a correctly seeded file becomes unwritable for the OTHER uid. `cat` into
    # the existing file keeps the inode, its owner and its mode.
    # The scratch file carries $$ so two uids never collide on one fixed
    # "${EVENTS_FILE}.tmp" path — that shared name has the same ownership trap
    # as the events file itself, and the loser could never truncate it.
    local count
    count=$(wc -l < "$EVENTS_FILE" 2>/dev/null || echo 0)
    if [ "$count" -gt "$MAX_EVENTS" ]; then
        local tmp="${EVENTS_FILE}.$$.tmp"
        if tail -n "$MAX_EVENTS" "$EVENTS_FILE" > "$tmp" 2>/dev/null; then
            cat "$tmp" > "$EVENTS_FILE" 2>/dev/null || \
                qlog_warn "Events trim failed: could not rewrite $EVENTS_FILE (owner/permission denied) — file keeps growing past $MAX_EVENTS"
        else
            qlog_warn "Events trim failed: could not write scratch file $tmp"
        fi
        rm -f "$tmp" 2>/dev/null
    fi

    qlog_info "EVENT [${etype}] ${message}"
    return 0
}

# ---------------------------------------------------------------------------
# Helper functions for detailed event messages
# ---------------------------------------------------------------------------
# These are only called when events actually fire (state changes), so the
# jq overhead is negligible — events are rare compared to 2s poll cycles.

# Get compact band list for a technology from carrier_components JSON
# Usage: bands=$(_ev_bands "LTE" "$t2_carrier_components") => "B3 + B7 + B28"
_ev_bands() {
    local tech="$1" cc="$2"
    [ -z "$cc" ] || [ "$cc" = "[]" ] && return
    printf '%s' "$cc" | jq -r --arg t "$tech" \
        '[.[] | select(.technology == $t) | .band] | if length > 0 then join(" + ") else empty end' 2>/dev/null
}

# Get band summary with total bandwidth for a technology
# Usage: summary=$(_ev_band_summary "LTE" "$t2_carrier_components") => "B3 + B7 + B28, 40 MHz"
_ev_band_summary() {
    local tech="$1" cc="$2"
    [ -z "$cc" ] || [ "$cc" = "[]" ] && return
    printf '%s' "$cc" | jq -r --arg t "$tech" '
        [.[] | select(.technology == $t)] |
        if length == 0 then empty
        else
            (map(.band) | join(" + ")) as $bands |
            (map(.bandwidth_mhz) | add) as $bw |
            if $bw > 0 then "\($bands), \($bw) MHz"
            else $bands end
        end
    ' 2>/dev/null
}

# Compute added/removed bands between prev and current carrier_components.
# Sets global: _diff_added, _diff_removed (comma-separated band strings)
# Usage: _ev_ca_diff "LTE" "$prev_ev_carrier_components" "$t2_carrier_components"
_ev_ca_diff() {
    local tech="$1" prev="$2" curr="$3"
    _diff_added=""
    _diff_removed=""
    [ -z "$prev" ] && prev="[]"
    [ -z "$curr" ] && curr="[]"

    local result
    result=$(jq -rn --arg t "$tech" --argjson p "$prev" --argjson c "$curr" '
        ([$c[] | select(.technology == $t) | .band] - [$p[] | select(.technology == $t) | .band] | join(", ")),
        ([$p[] | select(.technology == $t) | .band] - [$c[] | select(.technology == $t) | .band] | join(", "))
    ' 2>/dev/null)

    _diff_added=$(printf '%s\n' "$result" | head -n 1)
    _diff_removed=$(printf '%s\n' "$result" | tail -n 1)
}

# Round a latency value (e.g. "137.90286") to nearest integer ("138").
# Returns input unchanged if "null", empty, or non-numeric.
_ev_round_latency() {
    case "$1" in
        ""|null) printf '%s' "$1"; return 0 ;;
    esac
    awk -v v="$1" 'BEGIN { if (v+0 == v) printf "%.0f", v; else printf "%s", v }'
}

# Build a short network context string from current state
# Output: "5G-NSA: B3 + N41" or "LTE: B3" or "5G-SA: N41"
_ev_net_context() {
    if [ -n "$lte_band" ] && [ "$nr_state" = "connected" ] && [ -n "$nr_band" ]; then
        echo "${network_type}: ${lte_band} + ${nr_band}"
    elif [ "$nr_state" = "connected" ] && [ -n "$nr_band" ]; then
        echo "${network_type}: ${nr_band}"
    elif [ -n "$lte_band" ]; then
        echo "${network_type}: ${lte_band}"
    elif [ -n "$network_type" ]; then
        echo "$network_type"
    fi
}

# ---------------------------------------------------------------------------
# Settle debounce for discrete radio identifiers (band, PCI)
# ---------------------------------------------------------------------------
# Why this exists, because the naive version was shipped first and was wrong:
#
# The serving band and cell identity are compared against the previous poll
# sample. On a service drop the modem re-acquires by walking a ladder of
# coverage bands, camping on each for one or two samples before settling back
# on the band it started from. A raw inequality reports every rung. Measured on
# a live RM520N: 44 of the 50 slots in the event ring were band_change, the
# whole ring spanned 12.5 minutes, and one outage plus one 100% packet-loss
# episode were the only non-band history that survived. The user's actual
# problem had been evicted by the noise generated while diagnosing it.
#
# Two mechanics make that worse than it looks:
#
#   1. A blank reading is NOT a value. parse_serving_cell blanks these fields
#      whenever AT+QENG returns no usable line (parse_at.sh:113-119, :232-235),
#      which is exactly what happens during a drop. The old code let a blank
#      propagate into the previous-sample snapshot, so the return leg of every
#      re-acquisition compared a real band against "" and silently vanished. On
#      the live capture that hid 22 of ~66 transitions: B8 was departed 24
#      times and entered twice, which is impossible for a contiguous walk.
#      Here a blank is skipped outright: no observation, no counter movement.
#
#   2. Announcing a settled value must not invent a hop. The band really does
#      pass through the intermediate rungs, so "changed from B41 to B28" would
#      state a transition the radio never made. Callers phrase it as "settled
#      on X (was Y)" instead: both clauses stay true no matter how many rungs
#      were skipped, and no reader is told about a hop that did not happen.
#
# The counterpart hazard, and the reason return code 2 exists: a value that
# oscillates faster than the settle window never settles, so a hold-only rule
# would go SILENT on the most broken radio it could encounter. That is a worse
# failure than the noise it replaces. So churn is counted, and a caller that
# gets rc 2 reports the instability itself rather than the individual rungs.
#
# Usage:
#   _ev_settle <channel> <current-value>; rc=$?
#     rc 0 → settled onto a new value; read $_EV_SETTLED_TO / $_EV_SETTLED_FROM
#     rc 1 → nothing to report (blank, still settling, or unchanged)
#     rc 2 → churning; read $_EV_FLAP_N for the count in this window
#
# <channel> must be a bare identifier — it is interpolated into variable names.
# Per-channel state lives in poller globals, matching the existing latency and
# loss streak counters (qmanager_poller:131-135), which are likewise not
# persisted. A poller restart therefore re-settles rather than resuming, which
# costs one settle window of silence and keeps the positional cut -f decode in
# restore_event_state untouched.

# Consecutive real observations before a new value is announced. The measured
# poll cadence is ~3s (POLL_INTERVAL=2 is a sleep AFTER the cycle body), so 3
# samples is roughly 9 seconds of stability. Every intermediate rung in the
# live capture was held for 1 to 2 samples; the steady-state band held for 45
# consecutive samples. Hard-coded deliberately, NOT a config key: the CGI that
# writes quality_thresholds.json rebuilds it from scratch with exactly two keys
# (settings/quality_thresholds.sh), so a third would be erased on the user's
# next preset save, and install_backend only deploys config files that do not
# already exist, so an upgraded device would never receive the new seed.
EV_SETTLE_SAMPLES="${EV_SETTLE_SAMPLES:-3}"

# Churn reporting: this many candidate changes inside this many seconds emits
# one instability event, then the window restarts. Six changes in five minutes
# is well clear of a normal handoff rate and well under the ~44-per-12-minutes
# the live storm produced.
EV_FLAP_THRESHOLD="${EV_FLAP_THRESHOLD:-6}"
EV_FLAP_WINDOW="${EV_FLAP_WINDOW:-300}"

_ev_settle() {
    local _ch="$1" _cur="$2"
    local _hold _holdn _last _flapn _flapt _now
    _EV_SETTLED_FROM=""
    _EV_SETTLED_TO=""
    _EV_FLAP_N=0

    # A blank is an absent observation, not a new value. Leave every counter
    # exactly as it was so an outage cannot reset a settle in progress.
    [ -z "$_cur" ] && return 1

    eval "_hold=\${_ev_hold_${_ch}:-}"
    eval "_holdn=\${_ev_holdn_${_ch}:-0}"
    eval "_last=\${_ev_last_${_ch}:-}"

    if [ "$_cur" = "$_hold" ]; then
        _holdn=$((_holdn + 1))
    else
        # A new candidate. Count it as churn unless it is simply the value we
        # already announced coming back, which is a settle, not a flap.
        if [ "$_cur" != "$_last" ]; then
            eval "_flapn=\${_ev_flapn_${_ch}:-0}"
            eval "_flapt=\${_ev_flapt_${_ch}:-0}"
            _now=$(date +%s)
            if [ $((_now - _flapt)) -ge "$EV_FLAP_WINDOW" ]; then
                _flapn=1
                _flapt="$_now"
            else
                _flapn=$((_flapn + 1))
            fi
            eval "_ev_flapn_${_ch}=\$_flapn"
            eval "_ev_flapt_${_ch}=\$_flapt"
        fi
        _hold="$_cur"
        _holdn=1
    fi

    eval "_ev_hold_${_ch}=\$_hold"
    eval "_ev_holdn_${_ch}=\$_holdn"

    if [ "$_holdn" -ge "$EV_SETTLE_SAMPLES" ]; then
        # Settled. Clear the churn window either way: the radio has stopped
        # moving, so counting toward an instability report would be stale. The
        # report latch clears too, so a later episode is reported promptly
        # rather than being muted by the previous one.
        eval "_ev_last_${_ch}=\$_cur"
        eval "_ev_flapn_${_ch}=0"
        eval "_ev_flapr_${_ch}=0"
        if [ -n "$_last" ] && [ "$_cur" != "$_last" ]; then
            _EV_SETTLED_FROM="$_last"
            _EV_SETTLED_TO="$_cur"
            return 0
        fi
        # First settle after a cold start, or settled back onto the value we
        # already reported (the re-acquisition case). Adopt it silently.
        return 1
    fi

    # Still unsettled. If it has been churning all window, report that — but at
    # most once per window. Resetting only the counter is not enough: a radio
    # oscillating every sample re-reaches the threshold in another six changes,
    # which would rebuild the very storm this function exists to stop, at
    # warning severity instead of info. So the last report time is its own
    # latch, cleared on settle so a genuinely new episode is not muted.
    eval "_flapn=\${_ev_flapn_${_ch}:-0}"
    if [ "$_flapn" -ge "$EV_FLAP_THRESHOLD" ]; then
        local _flapr
        eval "_flapr=\${_ev_flapr_${_ch}:-0}"
        _now=$(date +%s)
        if [ "$_flapr" -eq 0 ] || [ $((_now - _flapr)) -ge "$EV_FLAP_WINDOW" ]; then
            _EV_FLAP_N="$_flapn"
            eval "_ev_flapn_${_ch}=0"
            eval "_ev_flapt_${_ch}=\$_now"
            eval "_ev_flapr_${_ch}=\$_now"
            return 2
        fi
    fi

    return 1
}

# Snapshot current state into prev_ev_* variables (called once after first parse)
snapshot_event_state() {
    prev_ev_network_type="$network_type"
    # Band and PCI keep their last known good value across a blank reading.
    # parse_serving_cell blanks all four whenever AT+QENG returns no usable
    # line (parse_at.sh:113-119, :232-235) — i.e. on every service drop — and
    # the previous unconditional copy propagated that blank, destroying the
    # baseline. The visible symptom was the "was ..." clause on the NR anchor
    # lost message (below, in detect_events) going empty precisely when a user
    # most wants to know which band they fell off.
    prev_ev_lte_band="${lte_band:-$prev_ev_lte_band}"
    prev_ev_lte_pci="${lte_pci:-$prev_ev_lte_pci}"
    prev_ev_nr_band="${nr_band:-$prev_ev_nr_band}"
    prev_ev_nr_pci="${nr_pci:-$prev_ev_nr_pci}"
    prev_ev_nr_state="$nr_state"
    prev_ev_modem_reachable="$modem_reachable"
    # The internet verdict keeps its last known good value across a blank or
    # null reading, for exactly the reason the band/PCI lines above do. A dead
    # or stale ping cache makes read_ping_data() reset conn_internet_available
    # to "null", while the emit guard in detect_data_connection_events()
    # requires prev == "true" before it will fire internet_lost. Copying that
    # null in unconditionally rewrote the baseline mid-outage, so the following
    # "false" compared against "null" and the alert was swallowed outright — no
    # event, and with it no SMS, no email and no Discord. `${x:-$prev}` alone is
    # not enough here: the reading is the four-character string "null", not an
    # empty one.
    case "$conn_internet_available" in
        ''|null) ;;
        *) prev_ev_internet="$conn_internet_available" ;;
    esac
    prev_ev_ca_active="$t2_ca_active"
    prev_ev_ca_count="$t2_ca_count"
    prev_ev_nr_ca_active="$t2_nr_ca_active"
    prev_ev_nr_ca_count="$t2_nr_ca_count"
    prev_ev_service_status="$service_status"
    prev_ev_cfun="$t1_cfun"
    prev_ev_carrier_components="$t2_carrier_components"

    # Persist for restart recovery (atomic .tmp + mv).
    # _tmp is derived inside the function so EVENT_STATE_FILE overrides at any
    # point (tests, future callers) keep the .tmp path in sync with the final.
    local _tmp="${EVENT_STATE_FILE}.tmp"
    jq -n \
        --arg net   "$prev_ev_network_type" \
        --arg lteb  "$prev_ev_lte_band" \
        --arg ltep  "$prev_ev_lte_pci" \
        --arg nrb   "$prev_ev_nr_band" \
        --arg nrp   "$prev_ev_nr_pci" \
        --arg nrs   "$prev_ev_nr_state" \
        --arg mr    "$prev_ev_modem_reachable" \
        --arg net2  "$prev_ev_internet" \
        --arg caa   "$prev_ev_ca_active" \
        --arg cac   "$prev_ev_ca_count" \
        --arg ncaa  "$prev_ev_nr_ca_active" \
        --arg ncac  "$prev_ev_nr_ca_count" \
        --arg svc   "$prev_ev_service_status" \
        --arg cc    "$prev_ev_carrier_components" \
        --arg cfun  "${prev_ev_cfun:-}" \
        '{
            network_type: $net, lte_band: $lteb, lte_pci: $ltep,
            nr_band: $nrb, nr_pci: $nrp, nr_state: $nrs,
            modem_reachable: $mr, internet: $net2,
            ca_active: $caa, ca_count: $cac,
            nr_ca_active: $ncaa, nr_ca_count: $ncac,
            service_status: $svc, carrier_components: $cc,
            cfun: $cfun
        }' > "$_tmp" 2>/dev/null && \
        mv "$_tmp" "$EVENT_STATE_FILE" 2>/dev/null
}

# Restore prev_ev_* from disk on poller startup. Sets events_initialized=true
# if state was loaded successfully, leaves it false otherwise (cold boot).
restore_event_state() {
    [ -s "$EVENT_STATE_FILE" ] || return 0

    local _data
    _data=$(jq -r '[
        (.network_type // ""),
        (.lte_band // ""),
        (.lte_pci // ""),
        (.nr_band // ""),
        (.nr_pci // ""),
        (.nr_state // ""),
        (.modem_reachable // ""),
        (.internet // ""),
        (.ca_active // ""),
        (.ca_count // ""),
        (.nr_ca_active // ""),
        (.nr_ca_count // ""),
        (.service_status // ""),
        (.carrier_components // ""),
        (.cfun // "")
    ] | @tsv' "$EVENT_STATE_FILE" 2>/dev/null) || return 0

    [ -z "$_data" ] && return 0

    prev_ev_network_type=$(printf '%s' "$_data" | cut -f1)
    prev_ev_lte_band=$(printf '%s' "$_data" | cut -f2)
    prev_ev_lte_pci=$(printf '%s' "$_data" | cut -f3)
    prev_ev_nr_band=$(printf '%s' "$_data" | cut -f4)
    prev_ev_nr_pci=$(printf '%s' "$_data" | cut -f5)
    prev_ev_nr_state=$(printf '%s' "$_data" | cut -f6)
    prev_ev_modem_reachable=$(printf '%s' "$_data" | cut -f7)
    prev_ev_internet=$(printf '%s' "$_data" | cut -f8)
    prev_ev_ca_active=$(printf '%s' "$_data" | cut -f9)
    prev_ev_ca_count=$(printf '%s' "$_data" | cut -f10)
    prev_ev_nr_ca_active=$(printf '%s' "$_data" | cut -f11)
    prev_ev_nr_ca_count=$(printf '%s' "$_data" | cut -f12)
    prev_ev_service_status=$(printf '%s' "$_data" | cut -f13)
    prev_ev_carrier_components=$(printf '%s' "$_data" | cut -f14)
    prev_ev_cfun=$(printf '%s' "$_data" | cut -f15)

    events_initialized=true
    qlog_info "Event detection state restored from $EVENT_STATE_FILE"
}

# ---------------------------------------------------------------------------
# SCC PCI change detection via temp JSON
# ---------------------------------------------------------------------------
# Compares current t2_carrier_components against saved state in PCI_STATE_FILE.
# Only called when t2_carrier_components string has changed (Tier 2 refresh).
detect_scc_pci_changes() {
    local prev_sccs curr_sccs

    # Build current SCC list: tech+band+pci for SCC entries only
    curr_sccs=$(printf '%s' "$t2_carrier_components" | \
        jq -c '[.[] | select(.type == "SCC") | {tech: .technology, band: .band, pci: .pci}]' 2>/dev/null)
    [ -z "$curr_sccs" ] && curr_sccs="[]"

    # Read previous state from file
    if [ -f "$PCI_STATE_FILE" ]; then
        prev_sccs=$(cat "$PCI_STATE_FILE" 2>/dev/null)
        [ -z "$prev_sccs" ] && prev_sccs="[]"
    else
        # First run — save current state, no events
        printf '%s\n' "$curr_sccs" > "$PCI_STATE_FILE"
        return
    fi

    # Compare each current SCC against previous (matched by tech+band)
    local i=0
    local curr_count
    curr_count=$(printf '%s' "$curr_sccs" | jq 'length')

    while [ "$i" -lt "$curr_count" ]; do
        local c_tech c_band c_pci p_pci
        c_tech=$(printf '%s' "$curr_sccs" | jq -r ".[$i].tech")
        c_band=$(printf '%s' "$curr_sccs" | jq -r ".[$i].band")
        c_pci=$(printf '%s' "$curr_sccs" | jq -r ".[$i].pci")

        # Find matching entry in previous state
        p_pci=$(printf '%s' "$prev_sccs" | \
            jq -r --arg t "$c_tech" --arg b "$c_band" \
            '[.[] | select(.tech == $t and .band == $b)] | .[0].pci | if . == null then empty else tostring end')

        # If previous PCI exists and differs, emit event
        if [ -n "$p_pci" ] && [ "$p_pci" != "null" ] && [ "$p_pci" != "$c_pci" ]; then
            append_event "scc_pci_change" \
                "$c_tech $c_band SCC cell handoff (PCI: $p_pci -> $c_pci)" "info"
        fi

        i=$((i + 1))
    done

    # Save current state for next comparison
    printf '%s\n' "$curr_sccs" > "$PCI_STATE_FILE"
}

# ---------------------------------------------------------------------------
# Data connection quality checks (debounced — 3 consecutive readings)
# ---------------------------------------------------------------------------
detect_data_connection_events() {
    # Suppress internet events during active watchcat recovery.
    # Prevents spurious internet_lost/restored events from recovery actions
    # (Tier 1 ifup/ifdown, Tier 2 CFUN toggle, Tier 3 SIM switch).
    # Also prevents email alerts from firing during recovery.
    if [ "$conn_during_recovery" = "true" ]; then
        prev_ev_internet="$conn_internet_available"   # keep state in sync
        return
    fi

    # Pick up any pending threshold reload from the CGI before evaluating quality.
    _qt_check_reload

    # --- Internet connectivity ---
    if [ "$conn_internet_available" != "$prev_ev_internet" ]; then
        if [ "$conn_internet_available" = "true" ] && [ "$prev_ev_internet" = "false" ]; then
            local restore_ctx=""
            if [ "$conn_latency" != "null" ] && [ -n "$conn_latency" ]; then
                restore_ctx=" (latency: $(_ev_round_latency "$conn_latency")ms)"
            fi
            append_event "internet_restored" "Internet connectivity restored${restore_ctx}" "info"
        elif [ "$conn_internet_available" = "false" ] && [ "$prev_ev_internet" = "true" ]; then
            local net_ctx
            net_ctx=$(_ev_net_context)
            local lost_detail=""
            [ -n "$net_ctx" ] && lost_detail=" ($net_ctx)"
            append_event "internet_lost" "Internet connectivity lost${lost_detail}" "warning"
        fi
    fi

    # --- High latency detection (threshold + debounce from quality_thresholds.json) ---
    # Skip when ping daemon is stale (conn_latency="null") — don't touch streaks
    if [ "$conn_latency" != "null" ] && [ -n "$conn_latency" ]; then
        # Use awk for decimal comparison (POSIX shell has no float math)
        if echo "$conn_latency" | awk -v t="$_qt_lat_thresh" '{exit !($1 > t)}'; then
            ev_high_lat_streak=$((ev_high_lat_streak + 1))
            if [ "$ev_high_lat_streak" -ge "$_qt_lat_debounce" ] && [ "$ev_lat_alerted" = "false" ]; then
                append_event "high_latency" \
                    "High latency detected ($(_ev_round_latency "$conn_latency")ms, avg $(_ev_round_latency "$conn_avg_latency")ms)" "warning"
                ev_lat_alerted=true
            fi
        else
            # Latency below threshold — recover if previously alerted
            if [ "$ev_lat_alerted" = "true" ]; then
                append_event "latency_recovered" \
                    "Latency recovered ($(_ev_round_latency "$conn_latency")ms)" "info"
            fi
            ev_high_lat_streak=0
            ev_lat_alerted=false
        fi
    fi

    # --- High packet loss detection (threshold + debounce from quality_thresholds.json) ---
    if [ "$conn_packet_loss" != "null" ] && [ -n "$conn_packet_loss" ]; then
        if [ "$conn_packet_loss" -ge "$_qt_loss_thresh" ] 2>/dev/null; then
            ev_high_loss_streak=$((ev_high_loss_streak + 1))
            if [ "$ev_high_loss_streak" -ge "$_qt_loss_debounce" ] && [ "$ev_loss_alerted" = "false" ]; then
                append_event "high_packet_loss" \
                    "High packet loss detected (${conn_packet_loss}%)" "warning"
                ev_loss_alerted=true
            fi
        else
            # Packet loss below threshold — recover if previously alerted
            if [ "$ev_loss_alerted" = "true" ]; then
                append_event "packet_loss_recovered" \
                    "Packet loss recovered (${conn_packet_loss}%)" "info"
            fi
            ev_high_loss_streak=0
            ev_loss_alerted=false
        fi
    fi
}

# Compare current state vs previous and emit events for any changes
detect_events() {
    # First cycle: populate previous state, don't generate events
    if [ "$events_initialized" = "false" ]; then
        snapshot_event_state
        # Initialize PCI state file with current SCCs
        if [ -n "$t2_carrier_components" ] && [ "$t2_carrier_components" != "[]" ]; then
            printf '%s' "$t2_carrier_components" | \
                jq -c '[.[] | select(.type == "SCC") | {tech: .technology, band: .band, pci: .pci}]' \
                > "$PCI_STATE_FILE" 2>/dev/null
        fi
        events_initialized=true
        qlog_debug "Event detection initialized"
        return
    fi

    # =====================================================================
    # Section 1: Network Mode events
    # =====================================================================

    # --- Modem reachability ---
    if [ "$modem_reachable" != "$prev_ev_modem_reachable" ]; then
        if [ "$modem_reachable" = "true" ]; then
            local net_ctx
            net_ctx=$(_ev_net_context)
            local restore_detail=""
            [ -n "$net_ctx" ] && restore_detail=" — $net_ctx"
            append_event "signal_restored" "Modem signal restored${restore_detail}" "info"
        else
            append_event "signal_lost" "Modem became unreachable" "warning"
            # Don't generate band/PCI events when modem goes away
            snapshot_event_state
            return
        fi
    fi

    # Skip detailed checks if modem is unreachable
    if [ "$modem_reachable" != "true" ]; then
        snapshot_event_state
        return
    fi

    # --- Airplane mode (CFUN transition) ---
    if [ "$t1_cfun" != "$prev_ev_cfun" ]; then
        if [ "$prev_ev_cfun" = "1" ] && { [ "$t1_cfun" = "0" ] || [ "$t1_cfun" = "4" ]; }; then
            append_event "airplane_mode" "Airplane mode enabled (CFUN=$t1_cfun)" "warning"
        elif { [ "$prev_ev_cfun" = "0" ] || [ "$prev_ev_cfun" = "4" ]; } && [ "$t1_cfun" = "1" ]; then
            append_event "airplane_mode" "Airplane mode disabled" "info"
        fi
    fi

    # --- Network mode change ---
    if [ -n "$network_type" ] && [ -n "$prev_ev_network_type" ] && \
       [ "$network_type" != "$prev_ev_network_type" ]; then
        # Determine if upgrade or downgrade: 5G-SA > 5G-NSA > LTE
        local mode_severity="info"
        case "$prev_ev_network_type-$network_type" in
            5G-SA-5G-NSA|5G-SA-LTE|5G-NSA-LTE) mode_severity="warning" ;;
        esac
        # Include current band context
        local mode_detail=""
        case "$network_type" in
            5G-NSA)
                [ -n "$lte_band" ] && [ -n "$nr_band" ] && mode_detail=" (${lte_band} + ${nr_band})"
                ;;
            5G-SA)
                [ -n "$nr_band" ] && mode_detail=" (${nr_band})"
                ;;
            LTE)
                [ -n "$lte_band" ] && mode_detail=" (${lte_band})"
                ;;
        esac
        append_event "network_mode" \
            "Network mode changed from $prev_ev_network_type to $network_type${mode_detail}" "$mode_severity"
    fi

    # =====================================================================
    # Section 2: Band Changes events
    # =====================================================================

    # --- LTE band change (settle-debounced, see _ev_settle) ---
    local _rc
    _ev_settle lte_band "$lte_band"; _rc=$?
    if [ "$_rc" -eq 0 ]; then
        local lte_band_detail=""
        [ -n "$lte_pci" ] && lte_band_detail=" (PCI $lte_pci)"
        append_event "band_change" \
            "LTE band settled on ${_EV_SETTLED_TO} (was ${_EV_SETTLED_FROM})${lte_band_detail}" "info"
    elif [ "$_rc" -eq 2 ]; then
        append_event "band_change" \
            "LTE band unstable — ${_EV_FLAP_N} changes in the last $((EV_FLAP_WINDOW / 60)) min" "warning"
    fi

    # --- LTE PCI change (PCC cell handoff, settle-debounced) ---
    _ev_settle lte_pci "$lte_pci"; _rc=$?
    if [ "$_rc" -eq 0 ]; then
        local lte_pci_ctx=""
        [ -n "$lte_band" ] && lte_pci_ctx=" on $lte_band"
        append_event "pci_change" \
            "LTE PCC cell handoff${lte_pci_ctx} (PCI ${_EV_SETTLED_FROM} -> ${_EV_SETTLED_TO})" "info"
    elif [ "$_rc" -eq 2 ]; then
        append_event "pci_change" \
            "LTE cell unstable — ${_EV_FLAP_N} handoffs in the last $((EV_FLAP_WINDOW / 60)) min" "warning"
    fi

    # --- NR state change (5G anchor gained/lost) ---
    if [ -n "$nr_state" ] && [ -n "$prev_ev_nr_state" ] && \
       [ "$nr_state" != "$prev_ev_nr_state" ]; then
        if [ "$nr_state" = "connected" ] && [ "$prev_ev_nr_state" != "connected" ]; then
            local nr_anchor_detail="($nr_band)"
            [ -n "$nr_pci" ] && nr_anchor_detail="($nr_band, PCI $nr_pci)"
            append_event "nr_anchor" "5G NR anchor acquired $nr_anchor_detail" "info"
        elif [ "$nr_state" != "connected" ] && [ "$prev_ev_nr_state" = "connected" ]; then
            local nr_lost_detail=""
            [ -n "$prev_ev_nr_band" ] && nr_lost_detail=" (was $prev_ev_nr_band)"
            append_event "nr_anchor" "5G NR anchor lost${nr_lost_detail}" "warning"
        fi
    fi

    # --- NR band / PCI changes (settle-debounced) ---
    # While the NR anchor is down there is nothing to observe, so feed the
    # helper a blank rather than skipping the call: counters freeze instead of
    # resetting, and an NSA drop-and-reacquire onto the same band stays silent.
    # The anchor itself is reported by the nr_anchor events above.
    local _nr_band_obs="" _nr_pci_obs=""
    if [ "$nr_state" = "connected" ]; then
        _nr_band_obs="$nr_band"
        _nr_pci_obs="$nr_pci"
    fi

    _ev_settle nr_band "$_nr_band_obs"; _rc=$?
    if [ "$_rc" -eq 0 ]; then
        local nr_band_detail=""
        [ -n "$nr_pci" ] && nr_band_detail=" (PCI $nr_pci)"
        append_event "band_change" \
            "NR band settled on ${_EV_SETTLED_TO} (was ${_EV_SETTLED_FROM})${nr_band_detail}" "info"
    elif [ "$_rc" -eq 2 ]; then
        append_event "band_change" \
            "NR band unstable — ${_EV_FLAP_N} changes in the last $((EV_FLAP_WINDOW / 60)) min" "warning"
    fi

    _ev_settle nr_pci "$_nr_pci_obs"; _rc=$?
    if [ "$_rc" -eq 0 ]; then
        local nr_pci_ctx=""
        [ -n "$nr_band" ] && nr_pci_ctx=" on $nr_band"
        append_event "pci_change" \
            "NR PCC cell handoff${nr_pci_ctx} (PCI ${_EV_SETTLED_FROM} -> ${_EV_SETTLED_TO})" "info"
    elif [ "$_rc" -eq 2 ]; then
        append_event "pci_change" \
            "NR cell unstable — ${_EV_FLAP_N} handoffs in the last $((EV_FLAP_WINDOW / 60)) min" "warning"
    fi

    # --- LTE CA changes ---
    if [ "$t2_ca_active" != "$prev_ev_ca_active" ]; then
        if [ "$t2_ca_active" = "true" ]; then
            local lte_ca_summary
            lte_ca_summary=$(_ev_band_summary "LTE" "$t2_carrier_components")
            if [ -n "$lte_ca_summary" ]; then
                append_event "ca_change" \
                    "LTE CA activated: $lte_ca_summary ($((t2_ca_count + 1)) carriers)" "info"
            else
                append_event "ca_change" \
                    "LTE CA activated ($((t2_ca_count + 1)) carriers)" "info"
            fi
        elif [ "$prev_ev_ca_active" = "true" ]; then
            local single_lte=""
            [ -n "$lte_band" ] && single_lte=" — single carrier ($lte_band)"
            append_event "ca_change" "LTE CA deactivated${single_lte}" "warning"
        fi
    elif [ "$t2_ca_active" = "true" ] && [ "$t2_ca_count" != "$prev_ev_ca_count" ]; then
        local prev_total=$((prev_ev_ca_count + 1))
        local new_total=$((t2_ca_count + 1))
        local ca_sev="info"
        [ "$new_total" -lt "$prev_total" ] && ca_sev="warning"

        # Compute which bands were added/removed
        _ev_ca_diff "LTE" "$prev_ev_carrier_components" "$t2_carrier_components"
        local ca_diff_detail=""
        if [ -n "$_diff_added" ] || [ -n "$_diff_removed" ]; then
            local parts=""
            [ -n "$_diff_added" ] && parts="+${_diff_added}"
            if [ -n "$_diff_removed" ]; then
                [ -n "$parts" ] && parts="$parts, "
                parts="${parts}-${_diff_removed}"
            fi
            ca_diff_detail=" ($parts)"
        else
            local lte_bands
            lte_bands=$(_ev_bands "LTE" "$t2_carrier_components")
            [ -n "$lte_bands" ] && ca_diff_detail=" (now $lte_bands)"
        fi
        append_event "ca_change" \
            "LTE carriers changed from $prev_total to $new_total${ca_diff_detail}" "$ca_sev"
    fi

    # --- NR CA changes ---
    if [ "$t2_nr_ca_active" != "$prev_ev_nr_ca_active" ]; then
        if [ "$t2_nr_ca_active" = "true" ]; then
            local nr_ca_summary
            nr_ca_summary=$(_ev_band_summary "NR" "$t2_carrier_components")
            if [ -n "$nr_ca_summary" ]; then
                append_event "ca_change" \
                    "NR CA activated: $nr_ca_summary ($((t2_nr_ca_count + 1)) NR carriers)" "info"
            else
                append_event "ca_change" \
                    "NR CA activated ($((t2_nr_ca_count + 1)) NR carriers)" "info"
            fi
        elif [ "$prev_ev_nr_ca_active" = "true" ]; then
            local single_nr=""
            [ -n "$nr_band" ] && single_nr=" — single carrier ($nr_band)"
            append_event "ca_change" "NR CA deactivated${single_nr}" "warning"
        fi
    elif [ "$t2_nr_ca_active" = "true" ] && [ "$t2_nr_ca_count" != "$prev_ev_nr_ca_count" ]; then
        local prev_total=$((prev_ev_nr_ca_count + 1))
        local new_total=$((t2_nr_ca_count + 1))
        local nr_ca_sev="info"
        [ "$new_total" -lt "$prev_total" ] && nr_ca_sev="warning"

        # Compute which NR bands were added/removed
        _ev_ca_diff "NR" "$prev_ev_carrier_components" "$t2_carrier_components"
        local nr_diff_detail=""
        if [ -n "$_diff_added" ] || [ -n "$_diff_removed" ]; then
            local parts=""
            [ -n "$_diff_added" ] && parts="+${_diff_added}"
            if [ -n "$_diff_removed" ]; then
                [ -n "$parts" ] && parts="$parts, "
                parts="${parts}-${_diff_removed}"
            fi
            nr_diff_detail=" ($parts)"
        else
            local nr_bands
            nr_bands=$(_ev_bands "NR" "$t2_carrier_components")
            [ -n "$nr_bands" ] && nr_diff_detail=" (now $nr_bands)"
        fi
        append_event "ca_change" \
            "NR carriers changed from $prev_total to $new_total${nr_diff_detail}" "$nr_ca_sev"
    fi

    # --- SCC PCI changes (detected on Tier 2 refresh) ---
    if [ "$t2_carrier_components" != "$prev_ev_carrier_components" ]; then
        detect_scc_pci_changes
    fi

    # =====================================================================
    # Section 3: Data Connection events
    # =====================================================================
    detect_data_connection_events

    # Update snapshot
    snapshot_event_state
}
